version: "3"

services:
  user-managment-api:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=user_management
